import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('Supabase credentials not found. Authentication will not work.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'recruitment-engine-auth',
  },
});

// Database types (will be generated by Supabase)
export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logoUrl: string | null;
          website: string | null;
          plan: 'free' | 'starter' | 'professional' | 'enterprise';
          isActive: boolean;
          createdAt: string;
        };
        Insert: Omit<Database['public']['Tables']['organizations']['Row'], 'id' | 'createdAt'>;
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>;
      };
      users: {
        Row: {
          id: string;
          email: string;
          fullName: string | null;
          avatarUrl: string | null;
          createdAt: string;
        };
      };
      organization_members: {
        Row: {
          id: string;
          organizationId: string;
          userId: string;
          role: 'owner' | 'admin' | 'recruiter' | 'viewer';
          joinedAt: string | null;
          createdAt: string;
        };
      };
    };
  };
};